# Generated by Django 6.0.7 on 2026-08-18 09:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_lease_electricity_charge_lease_gas_charge_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lease',
        ),
        migrations.AddField(
            model_name='invoice',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='financial_posting_status',
            field=models.CharField(default='not_posted', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gl_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='internet_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_payment_penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='utility_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='base_rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='RentalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_account_number', models.CharField(max_length=64, unique=True)),
                ('rent_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('parking', 'Parking'), ('storage', 'Storage')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=32)),
                ('billing_frequency', models.CharField(default='monthly', max_length=32)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('parking_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('utility_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('internet_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('default_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rent_escalation_applied', models.BooleanField(default=False)),
                ('escalation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('late_payment_penalty_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('late_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late interest rate per month.', max_digits=6)),
                ('gl_account', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=255)),
                ('financial_posting_status', models.CharField(default='not_posted', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rental_account', to='leases.lease')),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rental_account_number'],
                'unique_together': {('organization', 'rental_account_number')},
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='not_applicable', max_length=32)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rental_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='rentals.rentalaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='rental_account',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='rentals.rentalaccount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RentalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('increase', 'Increase'), ('decrease', 'Decrease'), ('escalation', 'Escalation'), ('correction', 'Correction')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('rental_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='rentals.rentalaccount')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
