# Generated by Django 6.0.7 on 2026-07-29 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_move_in_date_lease_move_out_date'),
        ('organizations', '0002_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lease',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lease',
            name='currency',
            field=models.CharField(default='ETB', max_length=8),
        ),
        migrations.AddField(
            model_name='lease',
            name='digital_signature_status',
            field=models.CharField(choices=[('not_signed', 'Not Signed'), ('signed', 'Signed')], default='not_signed', max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='early_termination_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='early_termination_notice_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='grace_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='insurance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='invoice_generation_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of the month invoices are generated.', null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='late_payment_penalty_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office'), ('warehouse', 'Warehouse')], max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='lease_version',
            field=models.CharField(default='V1.0', max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='maintenance_responsibility',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='parking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='pet_policy',
            field=models.CharField(blank=True, choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed'), ('case_by_case', 'Case-by-case')], max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewal_notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewal_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='renewal_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_escalation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_escalation_type',
            field=models.CharField(blank=True, choices=[('fixed_percent', 'Fixed %'), ('cpi_based', 'CPI-based')], max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='subletting_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='utility_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='Payment frequency.', max_length=16),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('awaiting_signature', 'Awaiting Signature'), ('active', 'Active'), ('renewal_pending', 'Renewal Pending'), ('renewed', 'Renewed'), ('amended', 'Amended'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Lease Agreement'.", max_length=255)),
                ('file', models.FileField(upload_to='leases/documents/')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.lease')),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
