# Generated by Django 6.0.7 on 2026-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_approval_date_lease_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='utility_charges',
        ),
        migrations.AddField(
            model_name='lease',
            name='electricity_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='gas_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='internet_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='invoice_generation_relative_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Used when term type is 'relative': days before the due date to generate the invoice.", null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='invoice_generation_term_type',
            field=models.CharField(choices=[('fixed', 'Fixed day of month'), ('relative', 'Relative to due date')], default='fixed', help_text='Fixed: generate on a specific day each month. Relative: generate N days before the due date.', max_length=16),
        ),
        migrations.AddField(
            model_name='lease',
            name='other_utility_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='invoice_generation_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Used when term type is 'fixed': day of the month invoices are generated.", null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_version',
            field=models.CharField(default='V1.0', editable=False, help_text='Auto-managed: V1.0 on creation, minor version bumps on every subsequent edit.', max_length=16),
        ),
    ]
