# Generated by Django 6.0.7 on 2026-08-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_remove_lease_utility_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='electricity_charge',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='gas_charge',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='internet_charge',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='other_utility_charge',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='water_charge',
        ),
    ]
