# Generated by Django 6.0.7 on 2026-08-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_remove_lease_electricity_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='electricity_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Electricity charge applicable to this lease. May initially be populated from Unit's standard electricity_charge but is stored independently.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='gas_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Gas charge applicable to this lease. May initially be populated from Unit's standard gas_charge but is stored independently.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='internet_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Internet charge applicable to this lease. May initially be populated from Unit's standard internet_charge but is stored independently.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='other_utility_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Other utility charge applicable to this lease.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Water charge applicable to this lease. May initially be populated from Unit's standard water_charge but is stored independently.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='Payment frequency for lease charges.', max_length=16),
        ),
        migrations.AlterField(
            model_name='lease',
            name='currency',
            field=models.CharField(default='ETB', help_text="Currency applicable to this lease's pricing.", max_length=8),
        ),
        migrations.AlterField(
            model_name='lease',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, help_text="Contractual monthly rent for this lease. This is independent from the Unit's standard/default rent.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='lease',
            name='parking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Parking fee applicable to this lease. The physical parking-space reference comes from the Unit.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security deposit agreed in this lease.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lease',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Contractual service charge for this lease. Independent from the Unit's standard service charge.", max_digits=12, null=True),
        ),
    ]
