# Generated by Django 6.0.7 on 2026-07-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Admin'), ('property_manager', 'Property Manager'), ('leasing_officer', 'Leasing Officer'), ('finance', 'Finance'), ('maintenance', 'Maintenance Staff')], max_length=32),
        ),
    ]
