# Generated by Django 6.0.7 on 2026-07-18 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=16)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('kyc_pending', 'KYC Verification Pending'), ('approved', 'Approved'), ('active', 'Active Tenant'), ('former', 'Former Tenant')], default='prospect', max_length=16)),
                ('full_name', models.CharField(help_text='Full legal name, or company name.', max_length=255)),
                ('national_id_or_business_reg', models.CharField(blank=True, help_text='National ID/passport for individuals, registration no. for companies.', max_length=64)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
