# Generated by Django 6.0.7 on 2026-07-29 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accessibility_requirements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='background_check_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged')], max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='blacklist_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_license_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_registration_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Company representative.', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='credit_check_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='nationality',
            field=models.CharField(blank=True, default='Ethiopian', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('phone', 'Phone')], max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('amharic', 'Amharic')], max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sub_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='TIN.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_code',
            field=models.CharField(blank=True, help_text="e.g. 'TNT-1001'.", max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_registration_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='woreda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full legal name (individual) or company name. Auto-filled from name parts / company name if left blank.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text='KYC Verification Status: Pending / Verified.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='national_id_or_business_reg',
            field=models.CharField(blank=True, help_text='National ID / Passport No. for individuals.', max_length=64),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(help_text='Mobile number.', max_length=32),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('application_submitted', 'Application Submitted'), ('kyc_verification', 'KYC Verification'), ('approved', 'Approved'), ('lease_signed', 'Lease Signed'), ('active_tenant', 'Active Tenant'), ('lease_renewal', 'Lease Renewal'), ('move_out', 'Move-Out'), ('former_tenant', 'Former Tenant')], default='prospect', max_length=32),
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'ID Copy'.", max_length=255)),
                ('file', models.FileField(upload_to='tenants/documents/')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
