# Generated by Django 6.0.7 on 2026-07-18 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
                ('number_of_floors', models.PositiveIntegerField(default=1)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Ground Floor', '5th Floor'", max_length=100)),
                ('floor_number', models.IntegerField(help_text='Numeric level; can be negative for basements.')),
                ('floor_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('parking', 'Parking'), ('office', 'Office')], default='residential', max_length=32)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('organization', 'building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Internal short code, e.g. PR001', max_length=32)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed-use'), ('industrial', 'Industrial')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_construction', 'Under Construction'), ('fully_occupied', 'Fully Occupied'), ('partially_occupied', 'Partially Occupied'), ('closed', 'Closed')], default='draft', max_length=32)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('property_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('organization', 'property', 'code')},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(help_text="e.g. 'A-101'", max_length=32)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('parking', 'Parking')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('vacant', 'Vacant'), ('reserved', 'Reserved'), ('leased', 'Leased / Occupied'), ('under_maintenance', 'Under Maintenance'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.floor')),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('organization', 'floor', 'unit_number')},
            },
        ),
    ]
