# Generated by Django 6.0.7 on 2026-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_merge_20260723_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='backup_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='cctv_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(default='ETB', max_length=8),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_protection_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='internet_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='managing_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_permit_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('leased', 'Leased'), ('managed', 'Managed')], max_length=16),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='vat_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='gross_floor_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built-up area (sqm).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Parking spaces.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Maintenance status.', max_length=16),
        ),
        migrations.AlterField(
            model_name='property',
            name='security_provider',
            field=models.CharField(blank=True, help_text='Security service.', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('under_construction', 'Under Construction'), ('ready_for_occupancy', 'Ready for Occupancy'), ('active', 'Active'), ('partially_occupied', 'Partially Occupied'), ('fully_occupied', 'Fully Occupied'), ('under_renovation', 'Under Renovation'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('sold', 'Sold'), ('decommissioned', 'Decommissioned')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(blank=True, help_text='Woreda / Zone.', max_length=100),
        ),
    ]
