# Generated by Django 6.0.7 on 2026-07-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        ('properties', '0004_property_backup_generator_property_cctv_installed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='access_control',
            field=models.CharField(blank=True, help_text="e.g. 'RFID Card', 'Keypad'.", max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='architectural_drawing_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='block_wing',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='building_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=16),
        ),
        migrations.AddField(
            model_name='building',
            name='building_height_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='building_permit_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('office', 'Office'), ('mixed_use', 'Mixed-use'), ('warehouse', 'Warehouse')], max_length=32),
        ),
        migrations.AddField(
            model_name='building',
            name='cctv_coverage',
            field=models.CharField(blank=True, help_text="e.g. 'Full Coverage', 'Partial', 'None'.", max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='cleaning_contractor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='emergency_exits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='fire_protection_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='generator_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='hvac_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='internet_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='main_electricity_meter',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='main_water_meter',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='maintenance_schedule',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=16),
        ),
        migrations.AddField(
            model_name='building',
            name='maintenance_supervisor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_basement_floors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='number_of_elevators',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='occupancy_certificate',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='building',
            name='parking_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='reception_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='rentable_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='security_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_construction', 'Under Construction'), ('under_maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='building',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='total_floor_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='water_supply',
            field=models.CharField(blank=True, help_text="e.g. 'Municipal', 'Borehole'.", max_length=100),
        ),
        migrations.CreateModel(
            name='BuildingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Building Permit'.", max_length=255)),
                ('file', models.FileField(upload_to='buildings/documents/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.building')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
