# Generated by Django 6.0.7 on 2026-07-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        ('properties', '0005_building_access_control_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='accessibility_features',
            field=models.CharField(blank=True, help_text="e.g. 'Wheelchair Access, Elevator'.", max_length=255),
        ),
        migrations.AddField(
            model_name='floor',
            name='cctv_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='floor',
            name='cleaning_schedule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16),
        ),
        migrations.AddField(
            model_name='floor',
            name='code',
            field=models.CharField(blank=True, help_text="e.g. 'F01'.", max_length=32),
        ),
        migrations.AddField(
            model_name='floor',
            name='common_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='emergency_exit_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='fire_safety_equipment',
            field=models.CharField(blank=True, help_text="e.g. 'Smoke Detectors, Fire Extinguishers'.", max_length=255),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floor',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='rentable_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='security_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='floor',
            name='total_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='utility_meter_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='accessibility_features',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='cctv_coverage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='currency',
            field=models.CharField(default='ETB', max_length=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_meter_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='gas_meter_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='internet_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='internet_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='maintenance_status',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_space',
            field=models.CharField(blank=True, help_text="e.g. 'P-101'.", max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='rentable_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='smart_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='smoke_detector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='storage_room',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_category',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed-use')], max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, help_text="e.g. 'Apartment 101'.", max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('retail', 'Retail'), ('office', 'Office'), ('storage', 'Storage')], max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='utility_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='utility_billing_method',
            field=models.CharField(blank=True, choices=[('metered', 'Metered'), ('fixed_rate', 'Fixed Rate'), ('included', 'Included')], max_length=16),
        ),
        migrations.AddField(
            model_name='unit',
            name='vat_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_meter_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('vacant', 'Vacant'), ('reserved', 'Reserved'), ('leased', 'Leased / Occupied'), ('expiring', 'Expiring'), ('under_maintenance', 'Under Maintenance / Cleaning'), ('blocked', 'Blocked')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('office', 'Office'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('villa', 'Villa'), ('hotel_room', 'Hotel Room'), ('parking', 'Parking')], max_length=32),
        ),
        migrations.CreateModel(
            name='UnitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Floor Plan'.", max_length=255)),
                ('file', models.FileField(upload_to='units/documents/')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record. Null if created by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization (property management company) that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.unit')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
