# Generated by Django 6.0.7 on 2026-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_floor_accessibility_features_floor_cctv_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='electricity_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='gas_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='internet_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='other_utility_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
