# Generated by Django 6.0.7 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_unit_electricity_charge_unit_gas_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='accessible_parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Accessible parking spaces.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='covered_parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Number of covered parking spaces.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='open_parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Number of open/outdoor parking spaces.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_notes',
            field=models.TextField(blank=True, help_text='Additional parking information, restrictions, or arrangements.'),
        ),
        migrations.AddField(
            model_name='property',
            name='visitor_parking_spaces',
            field=models.PositiveIntegerField(blank=True, help_text='Parking spaces reserved for visitors.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total parking spaces available across the property.', null=True),
        ),
    ]
